import type { Metadata } from 'next'
import './globals.css'

import { CookieConsent } from '@/components/cookie-consent'
import { TailwindIndicator } from '@/components/tailwind-indicator'
import { Toaster } from '@/components/ui/sonner'
import { VercelAnalytics } from '@/components/vercel-analytics'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <CookieConsent />
        <Toaster richColors closeButton />
        <TailwindIndicator />
        <VercelAnalytics />
      </body>
    </html>
  )
}
